# -*- coding: utf-8 -*-
"""Automation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KIvRq89Ko3Awm65W87q2CMUhZ7_OJEzA
"""

import requests
from bs4 import BeautifulSoup

# Step 1: Fixed webpage URL
url = "https://quotes.toscrape.com"

try:
    # Step 2: Send request
    response = requests.get(url)
    response.raise_for_status()

    # Step 3: Parse HTML
    soup = BeautifulSoup(response.text, "html.parser")

    # Step 4: Extract title
    title = soup.title.string

    print("Page Title:", title)

    # Step 5: Save title to a file
    with open("webpage_title.txt", "w", encoding="utf-8") as file:
        file.write(f"URL: {url}\n")
        file.write(f"Title: {title}\n")

    print("Title saved to webpage_title.txt")

except requests.exceptions.RequestException as e:
    print("Error fetching the webpage:", e)